# Generated by Django 3.1.7 on 2021-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20210306_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя команды')),
                ('players', models.CharField(max_length=255, verbose_name='Персонажи')),
                ('days', models.CharField(max_length=255, verbose_name='Дней в игре')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя игры')),
                ('complete', models.BooleanField(default=False, verbose_name='Завершена')),
                ('squads', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.squad', verbose_name='Команды')),
            ],
        ),
    ]
