# Generated by Django 3.1.7 on 2021-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_game_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='days',
            field=models.CharField(max_length=255, null=True, verbose_name='Дней в игре'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='players',
            field=models.CharField(max_length=255, null=True, verbose_name='Персонажи'),
        ),
    ]
