# Generated by Django 3.1.7 on 2021-03-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20210307_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='days',
            field=models.CharField(max_length=255, verbose_name='Дней в игре'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='players',
            field=models.CharField(max_length=255, verbose_name='Персонажи'),
        ),
    ]
