# Generated by Django 3.1.7 on 2021-03-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_auto_20210307_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skill_type',
            new_name='SkillType',
        ),
    ]
