# Generated by Django 3.1.7 on 2021-03-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_auto_20210307_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='magicSkill',
            field=models.ForeignKey(blank=True, limit_choices_to={'skilltype': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='women.skillcategory', verbose_name='Магическое умение'),
        ),
    ]
