# Generated by Django 3.1.7 on 2021-03-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_auto_20210307_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='magicSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magic_school', to='women.magicschool', verbose_name='Магическая школа'),
        ),
    ]
