# Generated by Django 3.1.7 on 2021-03-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_skillcategory_magicschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Раса')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Раса')),
                ('description', models.TextField(blank=True, verbose_name='Описание расы')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='women.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Расу',
                'verbose_name_plural': 'Расы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='Race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='women.race', verbose_name='Раса'),
        ),
        migrations.AddField(
            model_name='player',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language', to='women.language', verbose_name='Язык'),
        ),
    ]
