# Generated by Django 3.1.7 on 2021-03-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0016_auto_20210307_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.IntegerField(blank=True, null=True, verbose_name='Энергия')),
                ('regenEnergy', models.IntegerField(blank=True, null=True, verbose_name='Регенерация энергии')),
                ('haste', models.IntegerField(blank=True, null=True, verbose_name='Скорость')),
                ('hit', models.IntegerField(blank=True, null=True, verbose_name='Меткость')),
                ('dmg', models.IntegerField(blank=True, null=True, verbose_name='Урон')),
                ('arp', models.IntegerField(blank=True, null=True, verbose_name='Пробивание брони')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('regenHp', models.IntegerField(blank=True, null=True, verbose_name='Регенерация здоровья в бою')),
                ('regenHpDaily', models.IntegerField(blank=True, null=True, verbose_name='Дневная регенерация здоровья')),
                ('evade', models.IntegerField(blank=True, null=True, verbose_name='Уклонение')),
                ('armor', models.IntegerField(blank=True, null=True, verbose_name='Броня')),
                ('magicArmor', models.IntegerField(blank=True, null=True, verbose_name='Магическая броня')),
                ('magicResist', models.IntegerField(blank=True, null=True, verbose_name='Магическое сопротивление')),
                ('mp', models.IntegerField(blank=True, null=True, verbose_name='Мана')),
                ('regenMp', models.IntegerField(blank=True, null=True, verbose_name='Регенерация маны в бою')),
                ('regenMpDaily', models.IntegerField(blank=True, null=True, verbose_name='Дневная регенрация маны')),
                ('magicPenetration', models.IntegerField(blank=True, null=True, verbose_name='Магическое проникновение')),
                ('magicIgnore', models.IntegerField(blank=True, null=True, verbose_name='Пробивание магической брони')),
                ('magicDirDmg', models.IntegerField(blank=True, null=True, verbose_name='Прямой магический урон')),
                ('magicPeriodicDmg', models.IntegerField(blank=True, null=True, verbose_name='Периодический магический урон')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя персонажа')),
            ],
            options={
                'verbose_name': 'Тип экипировки',
                'verbose_name_plural': 'Типы экипировки',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id'], 'verbose_name': 'Игру', 'verbose_name_plural': 'Игры'},
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('lvl', models.IntegerField(verbose_name='Уровень')),
                ('handType', models.BooleanField(default=False, verbose_name='Двуручное')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equip_attr', to='women.equip', verbose_name='Атрибуты')),
                ('typeEquip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_equip', to='women.typeequip', verbose_name='Тип экипировки')),
            ],
            options={
                'verbose_name': 'Элемент экипировки',
                'verbose_name_plural': 'Экипировка',
                'ordering': ['name'],
            },
        ),
    ]
