# Generated by Django 3.1.7 on 2021-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0017_auto_20210308_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='rangeType',
            field=models.BooleanField(default=False, verbose_name='Дальнобойное'),
        ),
    ]
