# Generated by Django 3.1.7 on 2021-03-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0020_auto_20210308_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attr',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterField(
            model_name='player',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Attr_player', to='women.attr', verbose_name='Атрибуты'),
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(blank=True, null=True, verbose_name='Золото')),
                ('projectiles', models.IntegerField(blank=True, null=True, verbose_name='Снаряды')),
                ('bag', models.TextField(blank=True, verbose_name='Сумка')),
                ('amulet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amulet_player', to='women.equip', verbose_name='Амулет')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_player', to='women.equip', verbose_name='Книга')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest_armor', to='women.equip', verbose_name='Броня')),
                ('leftHand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_hand', to='women.equip', verbose_name='Левая рука')),
                ('rightHand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_hand', to='women.equip', verbose_name='Правая рука')),
                ('ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ring_player', to='women.equip', verbose_name='Кольцо')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентари',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_player', to='women.playerinventory', verbose_name='Инвентарь'),
        ),
    ]
