# Generated by Django 3.1.7 on 2021-03-08 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0021_auto_20210308_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='amulet',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amulet_player', to='women.equip', verbose_name='Амулет'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='book',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_player', to='women.equip', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='chest',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest_armor', to='women.equip', verbose_name='Броня'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='leftHand',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_hand', to='women.equip', verbose_name='Левая рука'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='rightHand',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_hand', to='women.equip', verbose_name='Правая рука'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='ring',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ring_player', to='women.equip', verbose_name='Кольцо'),
        ),
    ]
