# Generated by Django 3.1.7 on 2021-03-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0022_auto_20210308_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='leftHand',
            field=models.ForeignKey(blank=True, limit_choices_to={'typeEquip': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_hand', to='women.equip', verbose_name='Левая рука'),
        ),
    ]
