# Generated by Django 3.1.7 on 2021-03-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0023_auto_20210308_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='squadName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squad', to='women.squad', verbose_name='Команда'),
        ),
    ]
