# Generated by Django 3.1.7 on 2021-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0026_auto_20210308_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
