# Generated by Django 3.1.7 on 2021-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0027_quests_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='photo',
            field=models.ImageField(default='enemies/default.jpg', upload_to='enemies/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='players/default.png', upload_to='players/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
