# Generated by Django 3.1.7 on 2021-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0029_auto_20210310_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='attr',
            name='stunChance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шанс оглушения'),
        ),
        migrations.AddField(
            model_name='attr',
            name='vampiric',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент вампиризма'),
        ),
    ]
