# Generated by Django 3.1.7 on 2021-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0031_attr_cursed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='players',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название команды'),
        ),
    ]
