# Generated by Django 3.1.7 on 2021-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0037_auto_20210313_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='attr',
            name='name',
            field=models.CharField(default='ничей', max_length=255, verbose_name='Чьи атрибуты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='type',
            field=models.CharField(default='кто-то', max_length=255, verbose_name='Раса врага'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чей инвентарь'),
        ),
    ]
