# Generated by Django 3.1.7 on 2021-03-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0038_auto_20210314_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Attr_enemy', to='women.attr', verbose_name='Атрибуты'),
        ),
    ]
