# Generated by Django 3.1.7 on 2021-03-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0040_auto_20210314_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_attr', to='women.attr', verbose_name='Атрибуты'),
        ),
    ]
