# Generated by Django 3.1.7 on 2021-03-13 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0041_auto_20210314_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_enemy', to='women.attr', verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_enemy', to='women.playerinventory', verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='player',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_player', to='women.attr', verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_player', to='women.playerinventory', verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
