# Generated by Django 3.1.7 on 2021-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0043_auto_20210314_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='name',
            field=models.CharField(default='Нет', max_length=255, verbose_name='Чей инвентарь'),
        ),
    ]
