# Generated by Django 3.1.7 on 2021-03-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0046_auto_20210314_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Золото'),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='projectiles',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Снаряды'),
        ),
    ]
