# Generated by Django 3.1.7 on 2021-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0049_auto_20210314_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enemy_Stats', to='women.playerstats', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player_Stats', to='women.playerstats', verbose_name='Характеристики'),
        ),
    ]
