# Generated by Django 3.1.7 on 2021-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0050_auto_20210314_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='startlvl',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Стартовая уровень'),
        ),
    ]
