# Generated by Django 3.1.7 on 2021-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0051_race_startlvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dead',
            field=models.BooleanField(default=False, verbose_name='Мертв'),
        ),
    ]
