# Generated by Django 3.1.7 on 2021-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0052_player_dead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название местности')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('map', models.ImageField(upload_to='maps/%Y/%m/%d/', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Территорию',
                'verbose_name_plural': 'Территории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='243', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='maps',
            field=models.ManyToManyField(blank=True, null=True, to='women.Maps', verbose_name='Карта'),
        ),
    ]
