# Generated by Django 3.1.7 on 2021-03-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0054_auto_20210317_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maps',
        ),
        migrations.AddField(
            model_name='maps',
            name='game',
            field=models.ForeignKey(blank=True, limit_choices_to={'complete': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='women.game', verbose_name='Игра'),
        ),
    ]
