# Generated by Django 3.1.7 on 2021-04-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0057_auto_20210321_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
