# Generated by Django 3.1.7 on 2021-04-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0062_attr_type_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='attr_ch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_enemy_ch', to='women.attr', verbose_name='Временные атрибуты'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='attr_tt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_enemy_tt', to='women.attr', verbose_name='Итоговые атрибуты'),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_ch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_player_ch', to='women.attr', verbose_name='Временные атрибуты'),
        ),
        migrations.AddField(
            model_name='player',
            name='attr_tt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Attr_player_tt', to='women.attr', verbose_name='Итоговые атрибуты'),
        ),
    ]
