# Generated by Django 3.1.7 on 2021-04-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_rolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='plusRoll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='strRoll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sumRoll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
