# Generated by Django 3.1.7 on 2021-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210422_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='Гном', max_length=255, verbose_name='Имя персонажа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(default='players/default.png', upload_to='players/%Y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
